export { default as Home } from './home/Home'
export { default as Topics } from './topics/Topics'
export { default as Topic } from './topic/Topic'
export { default as Posts } from './posts/Posts'
export { default as Post } from './post/Post'
export { default as Popular } from './popular/Popular'
export { default as Bookmarks } from './bookmarks/Bookmarks'
export { default as Courses } from './courses/Courses'
export { default as Course } from './course/Course'
export { default as Createpost } from './createpost/Createpost'
export { default as Profile} from './profile/Profile'